### ISSUE TITLE
Mobile - Registration status togles itself automatically

### ISSUE THREAD

**Issue by lix229** [coffeexcode/capstone#79] opened 2021-03-08 01:32 UTC
# Summary
Cannot togle registration status for an event, after clicking it, the status will automatically togle back right away.

# Env
- iOS version: 14.4
- Using Expo Go App

# Logs and Issue recreation
## Logs
N/A
## Issue recreation
1. Scan the QR code to run the app
2. find any event
3. togle registration status
![IMG_FBAA03464969-1](https://user-images.githubusercontent.com/35265304/110263277-382fcf00-7f84-11eb-87d2-e91fe5b13d82.jpeg)

**Comment by enricoflorentino** [comment] 2021-03-25 23:10
Was not able to reproduce, closing

**Closed by enricoflorentino** 2021-03-25 23:10 UTC
